name: CI/CD Demo

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: install dependencies
        run: |
          pip3 install -r requirements.txt
      
      - name: run tests
        run: |
          pytest test/test.py
      
      - name: build docker image
        run: |
          docker build -t ashutosh-mishra/sample-apis:${{ github.sha }} .
      
      # - name: docker login
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: push docker image
      #   run: |
      #     docker push davejfranco/python-fastapi-demo:${{ github.sha }}

    outputs:
      image: ashutosh-mishra/sample-apis:${{ github.sha }}
  
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:

      - name: pull docker image
        run: |
          docker pull ashutosh-mishra/sample-apis:${{ github.sha }}
        
  
